"""first

Revision ID: 19d161589be5
Revises: 
Create Date: 2022-02-22 17:16:35.447646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19d161589be5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('namn', sa.String(length=80), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=False),
    sa.Column('postalcode', sa.String(length=10), nullable=False),
    sa.Column('position', sa.String(length=1), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Account_nr', sa.String(length=30), nullable=False),
    sa.Column('PersonId', sa.Integer(), nullable=False),
    sa.Column('Balance', sa.Integer(), nullable=True),
    sa.Column('Datum', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['PersonId'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Account_nr')
    )
    op.create_table('credit_card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cardtype', sa.String(length=30), nullable=False),
    sa.Column('number', sa.String(length=30), nullable=False),
    sa.Column('PersonId', sa.Integer(), nullable=False),
    sa.Column('Datum', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['PersonId'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('AccountID', sa.Integer(), nullable=False),
    sa.Column('PersonId', sa.Integer(), nullable=False),
    sa.Column('Amount', sa.Integer(), nullable=False),
    sa.Column('Datum', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['AccountID'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['PersonId'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('AccountID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('credit_card')
    op.drop_table('accounts')
    op.drop_table('person')
    # ### end Alembic commands ###
