"""first

Revision ID: 7af497b2dd43
Revises: 
Create Date: 2022-03-01 17:57:31.067184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7af497b2dd43'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('namn', sa.String(length=80), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=False),
    sa.Column('postalcode', sa.String(length=10), nullable=False),
    sa.Column('position', sa.String(length=1), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user_registration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('firstname', sa.String(length=40), nullable=False),
    sa.Column('lastname', sa.String(length=40), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('updates', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('email_confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('password', sa.String(length=255), server_default='', nullable=False),
    sa.Column('first_name', sa.String(length=100), server_default='', nullable=False),
    sa.Column('last_name', sa.String(length=100), server_default='', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Account_nr', sa.String(length=30), nullable=False),
    sa.Column('PersonId', sa.Integer(), nullable=False),
    sa.Column('Balance', sa.Integer(), nullable=True),
    sa.Column('Datum', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['PersonId'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Account_nr')
    )
    op.create_table('credit_card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cardtype', sa.String(length=30), nullable=False),
    sa.Column('number', sa.String(length=30), nullable=False),
    sa.Column('PersonId', sa.Integer(), nullable=False),
    sa.Column('Datum', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['PersonId'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('AccountID', sa.Integer(), nullable=False),
    sa.Column('PersonId', sa.Integer(), nullable=False),
    sa.Column('Amount', sa.Integer(), nullable=False),
    sa.Column('Datum', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['AccountID'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['PersonId'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('user_roles')
    op.drop_table('credit_card')
    op.drop_table('accounts')
    op.drop_table('users')
    op.drop_table('user_registration')
    op.drop_table('roles')
    op.drop_table('person')
    # ### end Alembic commands ###
