"""empty message

Revision ID: e90902689c24
Revises: 19d161589be5
Create Date: 2022-02-23 18:04:38.928109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e90902689c24'
down_revision = '19d161589be5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Account_nr', sa.String(length=30), nullable=False),
    sa.Column('PersonId', sa.Integer(), nullable=False),
    sa.Column('Balance', sa.Integer(), nullable=True),
    sa.Column('Datum', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['PersonId'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Account_nr')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('AccountID', sa.Integer(), nullable=False),
    sa.Column('PersonId', sa.Integer(), nullable=False),
    sa.Column('Amount', sa.Integer(), nullable=False),
    sa.Column('Datum', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['AccountID'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['PersonId'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('accounts')
    # ### end Alembic commands ###
